/**
 * Mapping of TheMealDB Area names to ISO 3166-1 alpha-2 country codes
 * TheMealDB hosts high-res 64px flag icons at:
 * https://www.themealdb.com/images/icons/flags/big/64/{code}.png
 */
export const AREA_FLAG_CODES: Record<string, string> = {
  afghan: "af",
  afghanistan: "af",
  albanian: "al",
  albania: "al",
  algerian: "dz",
  algeria: "dz",
  american: "us",
  "united states": "us",
  andorran: "ad",
  andorra: "ad",
  angolan: "ao",
  angola: "ao",
  "antiguan, barbudan": "ag",
  "antigua and barbuda": "ag",
  argentine: "ar",
  argentinian: "ar",
  argentina: "ar",
  armenian: "am",
  armenia: "am",
  aruban: "aw",
  aruba: "aw",
  australian: "au",
  australia: "au",
  austrian: "at",
  austria: "at",
  azerbaijani: "az",
  azerbaijan: "az",
  bahamian: "bs",
  bahamas: "bs",
  bangladeshi: "bd",
  bangladesh: "bd",
  barbadian: "bb",
  barbados: "bb",
  belgian: "be",
  belgium: "be",
  motswana: "bw",
  botswana: "bw",
  brazilian: "br",
  brazil: "br",
  british: "gb",
  "united kingdom": "gb",
  bulgarian: "bg",
  bulgaria: "bg",
  cambodian: "kh",
  cambodia: "kh",
  canadian: "ca",
  canada: "ca",
  caymanian: "ky",
  "cayman islands": "ky",
  chilean: "cl",
  chile: "cl",
  chinese: "cn",
  china: "cn",
  colombian: "co",
  colombia: "co",
  "costa rican": "cr",
  "costa rica": "cr",
  croatian: "hr",
  croatia: "hr",
  cuban: "cu",
  cuba: "cu",
  danish: "dk",
  denmark: "dk",
  dominican: "dm",
  dominica: "dm",
  dutch: "nl",
  netherlands: "nl",
  egyptian: "eg",
  egypt: "eg",
  estonian: "ee",
  estonia: "ee",
  filipino: "ph",
  philippines: "ph",
  french: "fr",
  france: "fr",
  german: "de",
  germany: "de",
  greek: "gr",
  greece: "gr",
  hungarian: "hu",
  hungary: "hu",
  indian: "in",
  india: "in",
  indonesian: "id",
  indonesia: "id",
  iranian: "ir",
  iran: "ir",
  irish: "ie",
  ireland: "ie",
  italian: "it",
  italy: "it",
  jamaican: "jm",
  jamaica: "jm",
  japanese: "jp",
  japan: "jp",
  kenyan: "ke",
  kenya: "ke",
  korean: "kr",
  "south korean": "kr",
  laotian: "la",
  laos: "la",
  lebanese: "lb",
  lebanon: "lb",
  malaysian: "my",
  malaysia: "my",
  mexican: "mx",
  mexico: "mx",
  moroccan: "ma",
  morocco: "ma",
  norwegian: "no",
  norway: "no",
  pakistani: "pk",
  pakistan: "pk",
  peruvian: "pe",
  peru: "pe",
  polish: "pl",
  poland: "pl",
  portuguese: "pt",
  portugal: "pt",
  russian: "ru",
  russia: "ru",
  "saudi arabian": "sa",
  "saudi arabia": "sa",
  singaporean: "sg",
  singapore: "sg",
  slovak: "sk",
  slovakia: "sk",
  spanish: "es",
  spain: "es",
  swedish: "se",
  sweden: "se",
  swiss: "ch",
  switzerland: "ch",
  syrian: "sy",
  syria: "sy",
  thai: "th",
  thailand: "th",
  tunisian: "tn",
  tunisia: "tn",
  turkish: "tr",
  turkey: "tr",
  ukrainian: "ua",
  ukraine: "ua",
  uruguayan: "uy",
  uruguay: "uy",
  venezuelan: "ve",
  venezuela: "ve",
  vietnamese: "vn",
  vietnam: "vn",
};

/**
 * Returns the URL to crystal-clear high-res vector flag SVG from FlagCDN,
 * or null if no mapping is found.
 */
export function getAreaFlagUrl(areaName: string): string | null {
  if (!areaName) return null;
  const normalized = areaName.trim().toLowerCase();
  const code = AREA_FLAG_CODES[normalized];
  if (!code) return null;
  return `https://flagcdn.com/${code}.svg`;
}
